language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'  
  - '10'
before_script:
  - greenkeeper-lockfile-update
  - npm --v
script: 
  - npm test
after_script: greenkeeper-lockfile-upload
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
